// Copyright 2026 Miek Gieben and the Golang pkcs11 Contributors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// SPDX-License-Identifier: BSD-3-Clause

//go:build ignore
// +build ignore

// const_generate.go parses pkcs11t.h and generates zconst.go.
// zconst.go is meant to be checked into git.

package main

import (
	"bufio"
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
	"strings"
)

func main() {
	file, err := os.Open("pkcs11t.h")
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()

	out := &bytes.Buffer{}
	fmt.Fprintf(out, header)

	scanner := bufio.NewScanner(file)
	fmt.Fprintln(out, "const (")
	for scanner.Scan() {
		// Fairly simple parsing, any line starting with '#define' will output
		// $2 = $3 and drop any UL (unsigned long) suffixes
		fields := strings.Fields(scanner.Text())
		if len(fields) < 3 {
			continue
		}
		if fields[0] != "#define" {
			continue
		}
		// fields[1] (const name) needs to be 3 chars, starting with CK
		if !strings.HasPrefix(fields[1], "CK") {
			continue
		}
		// special case for (~0UL) — C bitwise NOT of unsigned long, becomes ^uint(0) in Go
		if fields[2] == "(~0UL)" {
			fmt.Fprintln(out, fields[1], " = ", "^uint(0)")
			continue
		}
		value := strings.TrimSuffix(fields[2], "UL")
		// special case for things like: (CKF_ARRAY_ATTRIBUTE|0x00000211UL)
		if strings.HasSuffix(value, "UL)") {
			value = strings.Replace(value, "UL)", ")", 1)
		}
		// check for /* deprecated */ comment
		if len(fields) == 6 && fields[4] == "Deprecated" {
			fmt.Fprintln(out, fields[1], " = ", value, "// Deprecated")
			continue
		}

		fmt.Fprintln(out, fields[1], " = ", value)
	}

	if err := scanner.Err(); err != nil {
		log.Fatal(err)
	}
	fmt.Fprintln(out, ")")
	res, err := format.Source(out.Bytes())
	if err != nil {
		fmt.Fprintf(os.Stderr, "%s", out.String())
		log.Fatal(err)
	}
	f, err := os.Create("zconst.go")
	if err != nil {
		log.Fatal(err)
	}
	f.Write(res)

}

const header = `// Copyright 2026 Miek Gieben and the Golang pkcs11 Contributors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// SPDX-License-Identifier: BSD-3-Clause

// Code generated by "go run const_generate.go"; DO NOT EDIT.


package pkcs11

`
